---
title: "INTRO"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{INTRO}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
# PREUZIMANJE MINUTNIH PODATAKA -------------------------------------------

library(findata)
library(rvest)
library(tiledb)
library(RcppQuantuccia)
library(data.table)
```

# FMP CLOUD DATA

```{r}
fmp = FMP$new()
```


## Dukascopy

```{r}

# dc = Dukascopy$new()
# dc_symbols <- dc$get_symbols()
# dc_symbols[grep("SPY", dc_symbols$symbols), ]
# 
# dc$download_raw(save_path = "D:/dukascopy",
#                 symbols = c("AAPLUSUSD", "SPYUSUSD"),
#                 start_date = as.Date("2017-01-01"),
#                 end_date = Sys.Date() - 1)
# 
# download_raw
```



## Get minute data

```{r}
if (FALSE) {
  # SP100
  sp100 <- read_html("https://en.wikipedia.org/wiki/S%26P_100") |>
    html_elements(x = _, "table") |>
    (`[[`)(3) |>
    html_table(x = _, fill = TRUE)
  sp100_symbols <- c("SPY", "TLT", "GLD", "USO", sp100$Symbol)

  # SP500 symbols
  symbols <- fmp$get_sp500_symbols()
  symbols <- na.omit(symbols)
  symbols <- symbols[!grepl("/", symbols)]

  # merge
  symbols <- unique(union(sp100_symbols, symbols))

  # get minute data from FMP cloud
  fmp$get_minute_equities_tiledb(symbols = symbols,
                                 url = "s3://equity-usa-minute-fmpcloud",
                                 save_uri_hour = "s3://equity-usa-hour-fmpcloud",
                                 save_uri_daily = "s3://equity-usa-daily-fmpcloud",
                                 deep_scan = FALSE)
  
  # consolidate
  # tiledb:::libtiledb_array_consolidate(ctx = context_with_config@ptr, uri = "s3://equity-usa-daily-fmpprep")
  # tiledb:::libtiledb_array_vacuum(ctx = context_with_config@ptr, uri = "s3://equity-usa-daily-fmpprep")
}
```


